import { useEffect, useState } from 'react'

const KEY='els_lms_data_v11'
const LEGACY_KEYS=['els_lms_data_v10','els_lms_data_v9','els_lms_data_v8','els_lms_data_v7']
const assessmentTypes=['Direct Observation','Question and Answer','Personal Statement','Work Practice']
const unitCatalog=[
{id:'01',reference:'SCD/CCD/001/L2',title:'Introduction to the role of early years practitioner',type:'Mandatory'},
{id:'02',reference:'SCD/CCD/002/L2',title:'Legislations (The Laws), Policies and Procedures in Early Years',type:'Mandatory'},
{id:'03',reference:'SCD/CCD/003/L2',title:'Equality, Diversity and Inclusive Practice',type:'Mandatory'},
{id:'04',reference:'SCD/CCD/004/L2',title:'Safeguarding and Protection of Children in ECCDE Environment',type:'Mandatory'},
{id:'05',reference:'SCD/CCD/005/L2',title:'Language and Communication',type:'Mandatory'},
{id:'06',reference:'SCD/CCD/006/L2',title:'Lesson Planning in Early Years',type:'Mandatory'},
{id:'07',reference:'SCD/CCD/007/L2',title:'Children’s Learning Perspectives: Play',type:'Mandatory'},
{id:'08',reference:'SCD/CCD/008/L2',title:'Support Healthy Lifestyle for Children through the Provision of Food and Nutrition',type:'Mandatory'},
{id:'09',reference:'SCD/CCD/009/L2',title:'Observation, Assessment and Planning in ECCDE',type:'Mandatory'},
{id:'10',reference:'SCD/CCD/010/L2',title:'Teamwork',type:'Mandatory'},
{id:'11',reference:'SCD/CCD/011/L2',title:'Communication',type:'Mandatory'},
{id:'12',reference:'SCD/CCD/012/L2',title:'Record Keeping and Reporting',type:'Mandatory'},
{id:'13',reference:'SCD/CCD/013/L2',title:'Professional Development in ECCDE',type:'Optional'},
{id:'14',reference:'SCD/CCD/014/L2',title:'Children School Readiness',type:'Optional'},
{id:'15',reference:'SCD/CCD/015/L2',title:'Social Skills and Children Behaviour',type:'Optional'},
{id:'16',reference:'SCD/CCD/016/L2',title:'Child Physical Care and Development',type:'Optional'},
{id:'17',reference:'SCD/CCD/017/L2',title:'Support Healthy Lifestyle for Children through Exercise',type:'Optional'},
{id:'18',reference:'SCD/CCD/018/L2',title:'Child Development from Conception to Five Years',type:'Optional'},
{id:'19',reference:'ENT/CCD/019/001',title:'Planning for a Childcare Centre',type:'Optional'},
{id:'20',reference:'ENT/CCD/020/002',title:'Childcare Centre Development and Management',type:'Optional'}]

const defaultData={users:[{id:'u1',name:'Demo Student',email:'student@example.com',password:'student123',role:'student'},{id:'u2',name:'Demo Instructor',email:'instructor@example.com',password:'instructor123',role:'instructor'}],course:{title:'',description:'',manual:'',units:[],assessments:[],announcements:[],forums:[]}}

function uid(p='id'){return p+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function loadData(){const x=localStorage.getItem(KEY);if(!x){let d=structuredClone(defaultData);for(const k of LEGACY_KEYS){try{const old=JSON.parse(localStorage.getItem(k)||'null');if(old){if(Array.isArray(old.users))d.users=old.users;if(old.course)d.course={...d.course,...old.course,announcements:Array.isArray(old.course.announcements)?old.course.announcements:[]};break}}catch{}}localStorage.setItem(KEY,JSON.stringify(d));return d}return JSON.parse(x)}
function persist(d){localStorage.setItem(KEY,JSON.stringify(d))}

function Field({label,children}){return <div className="form-group"><label>{label}</label>{children}</div>}

export default function App(){
 const [data,setData]=useState(loadData)
 const [user,setUser]=useState(()=>{const id=sessionStorage.getItem('els_current');return id?loadData().users.find(u=>u.id===id)||null:null})
 const [role,setRole]=useState('student')
 const [authView,setAuthView]=useState('login')
 const [page,setPage]=useState('dashboard')
 const [modal,setModal]=useState(null)
 const [message,setMessage]=useState('')
 useEffect(()=>{persist(data)},[data])
 const update=fn=>setData(prev=>{const next=structuredClone(prev);fn(next);persist(next);return next})
 const login=(email,password)=>{const u=data.users.find(x=>x.email===email.trim().toLowerCase()&&x.password===password&&x.role===role);if(!u)return setMessage('Invalid email, password or account type.');setMessage('');setUser(u);sessionStorage.setItem('els_current',u.id);setPage('dashboard')}
 const logout=()=>{sessionStorage.removeItem('els_current');setUser(null);setAuthView('login')}
 if(!user)return <Auth role={role} setRole={setRole} view={authView} setView={setAuthView} data={data} update={update} login={login} message={message} setMessage={setMessage}/>
 return <div className="app"><header className="topbar"><div className="brand"><i className="fa-solid fa-graduation-cap"></i> Early Learning Services</div><div className="user-area"><span>{user.name}</span><div className="avatar">{user.name[0].toUpperCase()}</div><button className="btn btn-light" onClick={logout}>Logout</button></div></header><div className="layout"><aside className="sidebar"><div className="nav-title">Main Menu</div><nav className="nav"><Nav label="Dashboard" icon="fa-house" onClick={()=>setPage('dashboard')}/><Nav label="Teaching Manual" icon="fa-book" onClick={()=>setPage('teachingManual')}/><Nav label="Announcements" icon="fa-bullhorn" onClick={()=>setPage('announcements')}/><Nav label="Forum" icon="fa-comments" onClick={()=>setPage('forum')}/>{user.role==='instructor'&&<><Nav label="Level" icon="fa-layer-group" onClick={()=>setPage('level')}/><Nav label="Add Units" icon="fa-circle-plus" onClick={()=>setPage('units')}/><Nav label="Assessment Methods" icon="fa-clipboard-check" onClick={()=>setPage('assessments')}/></>}</nav></aside><main className="main"><Page page={page} user={user} data={data} update={update} openModal={setModal}/></main></div>{modal&&<Modal modal={modal} close={()=>setModal(null)} user={user} update={update} data={data}/>}</div>
}

function Nav({label,icon,onClick}){return <button onClick={onClick}><i className={`fa-solid ${icon} icon`}></i>{label}</button>}

function Auth({role,setRole,view,setView,data,update,login,message,setMessage}){
 const [name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[resetEmail,setResetEmail]=useState('')
 const register=()=>{if(!name.trim()||!email.trim()||!password)return setMessage('Please complete all fields.');const e=email.trim().toLowerCase();if(data.users.some(u=>u.email===e))return setMessage('An account with this email already exists.');update(d=>d.users.push({id:uid('u'),name:name.trim(),email:e,password,role}));setMessage('Account created. You can now log in.');setView('login');setPassword('')}
 const reset=()=>{const u=data.users.find(x=>x.email===resetEmail.trim().toLowerCase()&&x.role===role);if(!u)return setMessage('No matching account was found.');const p=window.prompt('Enter your new password:');if(!p)return;update(d=>{const target=d.users.find(x=>x.id===u.id);target.password=p});setMessage('Password changed.');setView('login')}
 return <div className="auth"><div className="auth-box"><h1>Early Learning Services</h1><p className="muted"><i className="fa-solid fa-child-reaching"></i> Early Childhood Learning Management System</p><div className="role-switch"><button className={role==='student'?'active':''} onClick={()=>{setRole('student');setMessage('')}}>Student</button><button className={role==='instructor'?'active':''} onClick={()=>{setRole('instructor');setMessage('')}}>Instructor</button></div>{message&&<div className="info-box">{message}</div>}{view==='login'&&<><Field label="Email"><input type="email" placeholder="Enter email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Password"><input type="password" placeholder="Enter password" value={password} onChange={e=>setPassword(e.target.value)}/></Field><button className="btn btn-primary" onClick={()=>login(email,password)}><i className="fa-solid fa-right-to-bracket"></i> Login</button><button className="btn btn-light" onClick={()=>{setView('register');setMessage('')}}>Create Account</button><p style={{textAlign:'center',marginTop:16}}><a href="#reset" onClick={e=>{e.preventDefault();setView('reset');setMessage('')}}>Forgot Password?</a></p></>}{view==='register'&&<><Field label="Full Name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Email"><input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="Password"><input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></Field><button className="btn btn-primary" onClick={register}>Create Account</button><button className="btn btn-light" onClick={()=>{setView('login');setMessage('')}}>Back to Login</button></>}{view==='reset'&&<><p className="muted">Enter your email to reset your password.</p><Field label="Email"><input type="email" value={resetEmail} onChange={e=>setResetEmail(e.target.value)}/></Field><button className="btn btn-primary" onClick={reset}>Send Reset Link</button><button className="btn btn-light" onClick={()=>{setView('login');setMessage('')}}>Back to Login</button></>}</div></div>
}

function Page({page,user,data,update,openModal}){switch(page){case'teachingManual':return <Manual user={user} data={data} update={update}/>;case'level':return <Level data={data} update={update}/>;case'units':return <Units user={user} data={data} update={update}/>;case'assessments':return <Assessments user={user} data={data} update={update}/>;case'announcements':return <Announcements user={user} data={data} openModal={openModal}/>;case'forum':return <Forum user={user} data={data} update={update} openModal={openModal}/>;default:return <Dashboard user={user} data={data}/>}}

function Dashboard({user,data}){const c=data.course;return <><h1 className="page-title">{user.role==='student'?'Student':'Instructor'} Dashboard</h1><p className="muted">Your course overview.</p><div className="cards"><div className="card"><div className="muted"><i className="fa-solid fa-layer-group stat-icon"></i>Level Courses</div><div className="stat">{c.title?1:0}</div>{c.title?<div className="info-box"><strong>{c.title}</strong><p>{c.description||'No description added yet.'}</p></div>:<p className="muted" style={{marginTop:12}}>No level has been set.</p>}</div><div className="card"><div className="muted"><i className="fa-solid fa-cubes stat-icon"></i>Units</div><div className="stat">{c.units.length}</div>{c.units.length?<div className="info-box">{c.units.map(u=><div key={u.id} style={{marginBottom:10}}><strong>{u.number}: {u.title}</strong> <span className="badge">{u.status}</span><p>{u.description||'Description to be added by the instructor.'}</p><small className="muted">Instructor: {u.instructorName||'Not assigned'}</small></div>)}</div>:<p className="muted" style={{marginTop:12}}>No units have been selected.</p>}</div><div className="card"><div className="muted"><i className="fa-solid fa-clipboard-check stat-icon"></i>Assessment Methods</div><div className="stat">{c.assessments.length}</div>{c.assessments.length?<div className="info-box">{c.assessments.map(a=><div key={a.id}>{a.type}</div>)}</div>:<p className="muted" style={{marginTop:12}}>No assessment methods have been selected.</p>}</div></div></>}

function Manual({user,data,update}){const [text,setText]=useState(data.course.manual||'');return <><h1 className="page-title">Teaching Manual</h1><p className="muted">{user.role==='instructor'?'Type or paste the course outline/manual below. It is saved in this browser and visible to students.':'Your instructor’s course outline is shown below.'}</p><div className="card">{user.role==='instructor'?<><Field label="Course outline / teaching manual"><textarea placeholder="Type or paste the teaching manual here..." value={text} onChange={e=>setText(e.target.value)}/></Field><button className="btn btn-primary" onClick={()=>{update(d=>d.course.manual=text.trim());alert('Teaching manual saved.')}}>Save Teaching Manual</button></>:data.course.manual?<div style={{whiteSpace:'pre-wrap'}}>{data.course.manual}</div>:<div className="empty">The teaching manual has not been added yet.</div>}</div></>}

function Level({data,update}){const [title,setTitle]=useState(data.course.title),[desc,setDesc]=useState(data.course.description);return <><h1 className="page-title">Level</h1><p className="muted">Set the title and description students will see in their dashboard.</p><div className="card"><Field label="Level title"><input placeholder="e.g. Level 2" value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Level description"><textarea placeholder="Describe this level..." value={desc} onChange={e=>setDesc(e.target.value)}/></Field><button className="btn btn-primary" onClick={()=>{if(!title.trim())return alert('Enter a level title.');update(d=>{d.course.title=title.trim();d.course.description=desc.trim()});alert('Level saved.')}}>Save Level</button></div></>}

function Units({user,data,update}){const mine=data.course.units.filter(u=>u.instructorId===user.id);const [unitId,setUnitId]=useState('01'),[title,setTitle]=useState(''),[status,setStatus]=useState('Mandatory'),[desc,setDesc]=useState('');const taken=data.course.units.find(u=>u.unitId===unitId);const save=()=>{if(!title.trim())return alert('Enter a unit title.');if(taken&&taken.instructorId!==user.id)return alert('This unit is already assigned to another instructor.');update(d=>{const e=d.course.units.find(u=>u.unitId===unitId);if(e){e.title=title.trim();e.status=status;e.description=desc.trim()}else d.course.units.push({id:uid('unit'),unitId,number:'Unit '+unitId,title:title.trim(),status,description:desc.trim(),instructorId:user.id,instructorName:user.name});d.course.units.sort((a,b)=>+a.unitId-+b.unitId)});setTitle('');setDesc('');alert('Unit saved. Students can now see it on their dashboard.')};return <><h1 className="page-title">Select Your Units</h1><p className="muted">Select a unit you will teach, provide its title and status, then add the description students should see. A unit can be assigned to one instructor.</p><div className="card"><Field label="Unit number"><select value={unitId} onChange={e=>setUnitId(e.target.value)}>{unitCatalog.map(u=>{const x=data.course.units.find(v=>v.unitId===u.id);return <option key={u.id} value={u.id} disabled={x&&x.instructorId!==user.id}>Unit {u.id}{x&&x.instructorId!==user.id?' (assigned)':''}</option>})}</select></Field><Field label="Unit title"><input placeholder="Enter the unit title" value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label="Unit status"><select value={status} onChange={e=>setStatus(e.target.value)}><option>Mandatory</option><option>Optional</option></select></Field><Field label="Unit description"><textarea placeholder="Describe what students will learn in this unit..." value={desc} onChange={e=>setDesc(e.target.value)}/></Field><button className="btn btn-primary" onClick={save}>Save Unit</button></div><div className="section"><h2>My Units</h2>{mine.length?<div className="table-wrap"><table><thead><tr><th>Unit</th><th>Status</th><th>Student-facing description</th><th></th></tr></thead><tbody>{mine.map(u=><tr key={u.id}><td><strong>{u.number}</strong><br/>{u.title}</td><td><span className="badge">{u.status}</span></td><td>{u.description||'No description added.'}</td><td><button className="btn btn-danger" onClick={()=>update(d=>{d.course.units=d.course.units.filter(x=>x.id!==u.id)})}>Remove</button></td></tr>)}</tbody></table></div>:<div className="card empty">You have not selected any units yet.</div>}</div></>}

function Assessments({user,data,update}){const [type,setType]=useState(assessmentTypes[0]);return <><h1 className="page-title">Assessment Methods</h1><p className="muted">Choose an assessment method to make it available to students.</p>{user.role==='instructor'&&<div className="card"><Field label="Assessment type"><select value={type} onChange={e=>setType(e.target.value)}>{assessmentTypes.map(x=><option key={x}>{x}</option>)}</select></Field><button className="btn btn-primary" onClick={()=>{update(d=>{if(!d.course.assessments.some(a=>a.type===type))d.course.assessments.push({id:uid('assessment'),type})});alert('Assessment method saved.')}}>Save Assessment Method</button></div>}<div className="section">{data.course.assessments.length?<div className="table-wrap"><table><thead><tr><th>Assessment method</th>{user.role==='instructor'&&<th></th>}</tr></thead><tbody>{data.course.assessments.map(a=><tr key={a.id}><td>{a.type}</td>{user.role==='instructor'&&<td><button className="btn btn-danger" onClick={()=>update(d=>{d.course.assessments=d.course.assessments.filter(x=>x.id!==a.id)})}>Remove</button></td>}</tr>)}</tbody></table></div>:<div className="card empty">No assessment methods have been added.</div>}</div></>}

function Announcements({user,data,openModal}){return <><h1 className="page-title">Announcements</h1><p className="muted">{user.role==='instructor'?'Create announcements for all students.':'Announcements from your instructors appear here.'}</p>{user.role==='instructor'&&<button className="btn btn-primary" onClick={()=>openModal('announcement')}><i className="fa-solid fa-bullhorn"></i> Create Announcement</button>}<div className="section">{data.course.announcements?.length?data.course.announcements.map(a=><div className="card" style={{marginBottom:12}} key={a.id}><strong>{a.title}</strong><p style={{marginTop:8,whiteSpace:'pre-wrap'}}>{a.message}</p><small className="muted">Posted by {a.author} · {a.date}</small></div>):<div className="card empty">No announcements yet.</div>}</div></>}

function Forum({user,data,update,openModal}){return <><h1 className="page-title">Forum</h1><p className="muted">{user.role==='instructor'?'Create topics and reply to students.':'Join your instructor’s forum topics and respond in chat.'}</p>{user.role==='instructor'&&<button className="btn btn-primary" onClick={()=>openModal('topic')}>Create Forum Topic</button>}<div className="section">{data.course.forums.length?data.course.forums.map(f=><ForumCard key={f.id} f={f} user={user} update={update}/>):<div className="card empty">No forum topics have been created yet.</div>}</div></>}
function ForumCard({f,user,update}){const [text,setText]=useState('');return <div className="card" style={{marginBottom:18}}><div className="section-head"><h2>{f.topic}</h2><span className="badge">Created by {f.createdBy}</span></div><div className="chat">{f.messages.length?f.messages.map(m=><div key={m.id} className={`chat-message ${m.userId===user.id?'mine':''}`}><strong>{m.user}</strong><div>{m.text}</div><small>{m.date}</small></div>):<div className="empty">No responses yet.</div>}</div><Field label="Chat response"><textarea placeholder="Write a response..." value={text} onChange={e=>setText(e.target.value)}/></Field><button className="btn btn-primary" onClick={()=>{if(!text.trim())return alert('Write a response.');update(d=>{const x=d.course.forums.find(x=>x.id===f.id);x.messages.push({id:uid('msg'),userId:user.id,user:user.name,text:text.trim(),date:new Date().toLocaleString()})});setText('')}}>Send Response</button></div>}

function Modal({modal,close,user,update}){const [title,setTitle]=useState(''),[text,setText]=useState('');const save=()=>{if(modal==='announcement'){if(!title.trim()||!text.trim())return alert('Enter an announcement title and message.');update(d=>d.course.announcements.unshift({id:uid('announcement'),title:title.trim(),message:text.trim(),author:user.name,date:new Date().toLocaleString()}))}else{if(!title.trim())return alert('Enter a topic title.');update(d=>{const f={id:uid('forum'),topic:title.trim(),createdBy:user.name,messages:[]};if(text.trim())f.messages.push({id:uid('msg'),userId:user.id,user:user.name,text:text.trim(),date:new Date().toLocaleString()});d.course.forums.unshift(f)})}close()};return <div className="modal" onClick={e=>e.target===e.currentTarget&&close()}><div className="modal-box"><h2>{modal==='announcement'?'Create Announcement':'Create Forum Topic'}</h2><Field label={modal==='announcement'?'Announcement title':'Topic'}><input placeholder={modal==='announcement'?'Enter a title':'Enter a topic title'} value={title} onChange={e=>setTitle(e.target.value)}/></Field><Field label={modal==='announcement'?'Message':'Opening message'}><textarea placeholder={modal==='announcement'?'Write the announcement...':'Start the discussion...'} value={text} onChange={e=>setText(e.target.value)}/></Field><div className="modal-actions"><button className="btn btn-light" onClick={close}>Cancel</button><button className="btn btn-primary" onClick={save}>{modal==='announcement'?'Publish Announcement':'Create Topic'}</button></div></div></div>}
